### PR TITLE
Improved README and added Uninstallation scripts for Linux/Mac

### PR DESCRIPTION
**Pull request by arghyagod-coder**
Added uninstalling scripts, go ahead

### CODE REVIEW

**Review by Shravan-1908 — CHANGES_REQUESTED** [review]
why did you create two different uninstallation scripts for Mac and Linux if the content of both the scripts is the same? remove one of the installation scripts.

**Comment by arghyagod-coder** [comment]
cuz u created two different scripts for linux and mac installation while they are basically the same 😂

**Comment by Shravan-1908** [comment]
No, the installation scripts are different. The Mac installation script downloads the Mac executable while the Linux one downloads the Linux executable. However, in the case of uninstallation, the scripts are the same.

**Review by Shravan-1908 — APPROVED** [review]

**Comment by arghyagod-coder** [comment]
ADDED AUR SUPPORT!!! 🥳

**Pull request merged**
